| ID | Type | Description | Priority | Acceptance Criteria | Rationale |
|---|---|---|---|---|---|
| FR-001 | Functional | The system shall parse structured JSON audit logs, identify and mask PII fields (SSNs, credit cards) before persisting records to storage | High | Pass: masked audit log saved with SHA-256 integrity hash; Fail: cleartext credit card number stored in database | GDPR mandates PII minimization at rest |
| FR-002 | Functional | The system shall allow the Compliance Officer to define and edit PII masking rules (field name/pattern to masking strategy) via a configuration interface | High | Pass: new rule applied to next ingested log within 5 minutes; Fail: rule not applied | Masking rules vary by client/regulation and must be configurable, not hardcoded |
| FR-003 | Functional | The system shall allow the Security Auditor to search and filter audit logs by date range, actor ID, event type, and severity | High | Pass: correct result set returned for given filters; Fail: missing or incorrect records | Auditors need targeted investigation, not full-log scanning |
| FR-004 | Functional | The system shall generate a cryptographically signed, immutable export of audit logs for a specified date range | High | Pass: export file generated with verifiable digital signature; Fail: export is unsigned or mutable | Exports serve as legal or regulatory evidence and must be tamper-evident |
| FR-005 | Functional | The system shall verify the integrity of a previously generated export on demand and flag any tampering | Medium | Pass: correctly distinguishes valid vs altered exports; Fail: false positive or false negative | Auditors must be able to trust exports even months after generation |
| NFR-001 | Performance & Security | Audit log query endpoints must support complex filtering across 10 million historical records in under 1 second | High | Benchmarking tests confirm target latency and security standards under simulated peak load | Compliance queries during active audits are time-sensitive |
| NFR-002 | Security | All audit logs must be encrypted at rest (AES-256) and in transit (TLS 1.2+); stored logs must be immutable (WORM storage) | High | Pass: penetration test finds no cleartext exposure and no in-place log edits possible | Regulatory requirement (GDPR Art. 32) — audit logs themselves contain sensitive data |
